name = "PseudoGamma"
uuid = "3cb8af22-bcb6-49d5-810a-fde949a5ef89"
authors = ["Joris Pinkse <pinkse@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Aqua = "0.7"
SpecialFunctions = "2.3"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
