name = "PseudoGamma"
uuid = "3cb8af22-bcb6-49d5-810a-fde949a5ef89"
authors = ["Joris Pinkse <pinkse@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
